server:
  port: 8080

spring:
  application:
    name: stemshop

  datasource:
    url: jdbc:postgresql://localhost:5432/stemshop
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true